name: aeweb
description: Deploy websites on Archethic decentralized network to avoid censorship, increase security and have high-availability and resiliency.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '3.7.3'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Localization
  intl: ^0.17.0

dev_dependencies:

  flutter_lints: ^2.0.1
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl_generator: ^0.4.1

flutter:
  uses-material-design: true
