name: aeweb
description: Deploy websites on Archethic decentralized network to avoid censorship, increase security and have high-availability and resiliency.
publish_to: "none"

version: 0.0.11+9

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  archethic_dapp_framework_flutter: ^0.0.0
  #archethic_dapp_framework_flutter:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-dapp-framework-flutter.git
  #    ref: main
  #archethic_dapp_framework_flutter:
  #  path: ../archethic-dapp-framework-flutter

  # A client dart library to interact with Archethic Wallet RPC API.
  archethic_wallet_client: ^1.0.0
  #archethic_wallet_client:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-wallet-client-dart.git
  #    ref: dev

  # Compression
  archive: ^3.4.10

  # Common util classes for Strings, Dates, X509, PKCS, Cryptographie and more.
  basic_utils: ^5.7.0

  # Collections and utilities functions and classes related to collections.
  collection: ^1.18.0

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.3

  # A flutter package to let users easily add a dashed border around any widget.
  dotted_border: ^2.1.0

  # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
  file_picker: ^8.0.0+1

  # A package to get humanized file sizes. Translate raw file size into human readable strings
  filesize: ^2.0.1

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.5.0

  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
  flutter_staggered_grid_view: ^0.7.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.10+1

  # A tree widget for Flutter that can be used to display nested, hierarchical data. It includes a number of features like styling labels, icons, and import and export utilities.
  flutter_treeview: ^1.0.7+1

  # Annotations for freezed
  freezed_annotation: ^2.4.1

  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^13.2.1

  # Gradient borders for inputs and containers. Borders package integrated with a basic flutter widgets as a container and input decorations. Easy in use, platform independent.
  gradient_borders: ^1.0.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: any

  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.1

  # A Flutter plugin for rendering an animated and customizable starfield on a dark background.
  lit_starfield: ^0.1.1

  # A collection loading animations written in pure dart. Out of the box, no extra dependency.
  loading_indicator: ^3.1.1

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^4.2.0

  # A string-based path manipulation library. All of the path operations you know and love, with solid support for Windows, POSIX (Linux and Mac OS X), and the web.
  path: ^1.9.0

  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter
  phoenix_socket: ^0.7.0

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.3.5

  # Bar indicator made of a series of selected and unselected steps
  step_progress_indicator: ^1.0.2

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.2.5

  # Wave animation
  wave: ^0.2.2

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.8
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.7
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.4.0
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.25.2

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: PPTelegraf
      fonts:
        - asset: assets/fonts/PPTelegraf-Ultralight.otf
          weight: 200
        - asset: assets/fonts/PPTelegraf-Light.otf
          weight: 300
        - asset: assets/fonts/PPTelegraf-Regular.otf
          weight: 400
        - asset: assets/fonts/PPTelegraf-Medium.otf
          weight: 500
        - asset: assets/fonts/PPTelegraf-Semibold.otf
          weight: 600
        - asset: assets/fonts/PPTelegraf-Bold.otf
          weight: 700
        - asset: assets/fonts/PPTelegraf-Ultrabold.otf
          weight: 800
        - asset: assets/fonts/PPTelegraf-Black.otf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Iconsax
      fonts:
        - asset: assets/fonts/aedappfm.Iconsax.ttf
